name: deploy
on:
  push:
    branches:
      - main
  inputs:
     SP_USERNAME: 
       default: "sp-ns-username"
       
jobs:
  build:
    name: ns-build
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: sabhahit
          repo: child-pipeline
          workflow_file_name: child.yml
          github_token: ${{ secrets.my_ptoken }}
          ref: main
          
          
    
    
    
    
      
