# test
name: deploy
on:
  workflow_dispatch:
    inputs:
       SP_USERNAME: 
         default: "sp-ns-username"
env:
  env_var: dev
  
jobs:
  build:
    name: ns-build
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: sabhahit
          repo: child-pipeline
          workflow_file_name: child.yml
          github_token: ${{ secrets.my_ptoken }}
          ref: main
  build1:
    uses: sabhahit/child-pipeline/.github/workflows/child.yml@main
    with:
      image_name: my_image
      tag: my_tag
    
          
    
    
    
    
      
